# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: go-release-playground
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
brews:
 -
  name: go-release-playground
  ids:
  - go-release-playground
  goarm: 6
  github:
    owner: tomchavakis
    name: go-release-playground
  url_template: "https://github.com/tomchavakis/go-release-playground/releases/{{ .Tag }}/{{ .ArtifactName }}"
  commit_author:
      name: tomchavakis
      email: tomchavakis@gmail.com
  folder: Formula
  homepage: "https://github.com/tomchavakis/go-release-playground"
  description: "Command line demo"
  install: bin.install "go-release-playground"
builds:
- goos:
  - linux
  - darwin
  goarch:
  - amd64
  - "386"
  goarm:
  - "6"
  main: .
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: go-release-playground
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
signs:
-
  cmd: gpg
  args:
  - --output
  - $signature
  - --detach-sig
  - $artifact
  signature: ${artifact}.sig
  artifacts: none
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
