# This file was generated by GoReleaser. DO NOT EDIT.
class GoReleasePlayground < Formula
  desc "Command line demo"
  homepage "https://github.com/tomchavakis/go-release-playground"
  version "1.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/tomchavakis/go-release-playground/releases/download/v1.0.3/go-release-playground_Darwin_x86_64.tar.gz"
    sha256 "843982b84d6ab9aa66dc37d1902d4bc3a4438a4405f0b42ee30fcc9274727275"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/tomchavakis/go-release-playground/releases/download/v1.0.3/go-release-playground_Linux_x86_64.tar.gz"
      sha256 "5be4a0851830a42488444512ffc150b1e204a9a0e8b53290b03e9e2ed949376a"
    end
  end

  def install
    bin.install "go-release-playground"
  end

  test do
    system "#{bin/go-release-playground}"
  end
end
