# This file was generated by GoReleaser. DO NOT EDIT.
class GoReleasePlayground < Formula
  desc "Command line demo"
  homepage "https://github.com/tomchavakis/go-release-playground"
  version "1.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/tomchavakis/go-release-playground/releases/download/v1.0.4/go-release-playground_Darwin_x86_64.tar.gz"
    sha256 "53d4dfb0f1744ea0c81a7d27c9533a9c4c525f0be3485e542b4830ff5d607201"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/tomchavakis/go-release-playground/releases/download/v1.0.4/go-release-playground_Linux_x86_64.tar.gz"
      sha256 "976fcbbb58fe57f114b8c9c474309ab6d652129b6b412579cf74a8fcc76b3f42"
    end
  end

  def install
    bin.install "go-release-playground"
  end

  test do
    system "#{bin/go-release-playground}"
  end
end
