# This file was generated by GoReleaser. DO NOT EDIT.
class GoReleasePlayground < Formula
  desc "Command line demo"
  homepage "https://github.com/tomchavakis/go-release-playground"
  version "1.0.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/tomchavakis/go-release-playground/releases/download/v1.0.6/go-release-playground_Darwin_x86_64.tar.gz"
    sha256 "70c8178d16a21bb3e3c2eedd8f0c76fbbb3d88ddfb8eee840109fef8447be277"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/tomchavakis/go-release-playground/releases/download/v1.0.6/go-release-playground_Linux_x86_64.tar.gz"
      sha256 "4ef0ea675db710d38cca131ca90fe1ca5a1f1c34afa2fb4f57572d5df2a99c5f"
    end
  end

  def install
    bin.install "go-release-playground"
  end

  test do
    system "#{bin/go-release-playground}"
  end
end
